
#modulo php
php:
    build: docker
    volumes:
        - .:/var/www/empleados  
    links:
        - database
    environment:
      - "DB_PORT=3306"
      - "DB_HOST=database"
    ports:
      - "9000:9000"

#servidor web
web:
    image: nginx:1.14
    ports:
        - "80:80"
    volumes:
        - .:/var/www/empleados
        - ./site.conf:/etc/nginx/conf.d/default.conf
    links:
        - php

# base de datos
database:
    image: mysql:5.6
    volumes:
        - ./dbdata:/var/lib/mysql
    environment:
        - "MYSQL_DATABASE=empleados"
        - "MYSQL_USER=devuser"
        - "MYSQL_PASSWORD=toor"
        - "MYSQL_ROOT_PASSWORD=toor"
    ports:
        - "3306:3306"
#    command: mysql -u root -ptoor -D pined < /var/lib/mysql/pined_pp.sql
